In [1]:
import seaborn as sns
import pandas as pd
import numpy as np

In [4]:
#load count matrix (normalized)
counts_genes_norm = pd.read_csv("results_gene_counts_normalized_only_female_231212.csv")  
counts_genes_norm.rename(columns={"Unnamed: 0": "GENEID"}, inplace = True)
#rearrange columns
counts_genes_norm = counts_genes_norm[['GENEID', 
              'filtered_S1_quant_filtered',
              'filtered_S2_quant_filtered',
              'filtered_S4_quant_filtered',
              'filtered_S9_quant_filtered',
              'filtered_S11_quant_filtered',
              'filtered_S12_quant_filtered',]]

In [5]:
counts_genes_norm

,GENEID,filtered_S1_quant_filtered,filtered_S2_quant_filtered,filtered_S4_quant_filtered,filtered_S9_quant_filtered,filtered_S11_quant_filtered,filtered_S12_quant_filtered
0,ENSMUSG00000000001,6306.111096,5526.774801,5480.699490,6986.230785,7187.287490,7434.045727
1,ENSMUSG00000000003,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2,ENSMUSG00000000028,159.305235,138.436746,148.558981,165.844405,222.043307,243.453262
3,ENSMUSG00000000037,33.598975,40.040854,34.099580,63.756948,8.988655,20.360731
4,ENSMUSG00000000049,2.907095,0.000000,0.000000,0.911894,13.046878,1.118252
...,...,...,...,...,...,...,...
35677,ENSMUSG00000118670,3.013149,2.354209,3.994415,0.971993,3.506734,3.354749
35678,ENSMUSG00000118671,244.995201,240.379153,217.600614,388.964773,192.249070,222.314314
35679,ENSMUSG00000118672,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
35680,ENSMUSG00001074846,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
35681,ENSMUSG00002076083,529.303073,705.012290,631.715220,594.878518,642.842869,570.853835

In [8]:
#load results table
res_genes = pd.read_csv("gene_resAnno_only_female.csv", 
                        usecols = ['Unnamed: 0','GENENAME', "log2FoldChange", "padj", "pvalue"])  
res_genes.rename(columns={"Unnamed: 0": "GENEID"}, inplace=True)

In [9]:
res_genes

                   GENEID  log2FoldChange    pvalue      padj GENENAME
0      ENSMUSG00000000001        0.319575  0.000157  0.004735    Gnai3
1      ENSMUSG00000000003             NaN       NaN       NaN     Pbsn
2      ENSMUSG00000000028        0.496340  0.018064  0.128084    Cdc45
3      ENSMUSG00000000037       -0.258078  0.674981       NaN    Scml2
4      ENSMUSG00000000049        2.376936  0.197439       NaN     Apoh
...                   ...             ...       ...       ...      ...
35677  ENSMUSG00000118670       -0.266241  0.837295       NaN      NaN
35678  ENSMUSG00000118671        0.196333  0.435403  0.727331    EPPK1
35679  ENSMUSG00000118672             NaN       NaN       NaN     Muc4
35680  ENSMUSG00001074846             NaN       NaN       NaN      NaN
35681  ENSMUSG00002076083       -0.045596  0.743549  0.910018   Klhl17

[35682 rows x 5 columns]

In [10]:
#gene lists
gene_list =  ["Cacna1a",
                    "Cacna1b",
                    "Cacna1c",
                    "Cacna1d",
                    "Cacna1e",
                    "Cacna1f",
                    "Cacna1g",
                    "Cacna1h",
                    "Cacna1i",
                    "Cacna2d1",
                    "Cacna2d2",
                    "Cacnb1",
                    "Cacnb2",
                    "Cacnb3",
                    "Cacnb4"
                    ]

goi = res_genes[res_genes["GENENAME"].isin(gene_list)]

In [11]:
goi.sort_values(by=["GENENAME"], ascending=True)

,GENEID,log2FoldChange,pvalue,padj,GENENAME
9696,ENSMUSG00000034656,-0.704451,1.223237e-01,3.976461e-01,Cacna1a
673,ENSMUSG00000004113,0.799207,4.940770e-02,2.316534e-01,Cacna1b
14851,ENSMUSG00000051331,0.200981,9.734339e-02,3.479333e-01,Cacna1c
1674,ENSMUSG00000015968,0.620129,9.718218e-04,1.817157e-02,Cacna1d
672,ENSMUSG00000004110,0.596897,4.860274e-01,NaN,Cacna1e
8133,ENSMUSG00000031142,-1.218559,4.433487e-01,NaN,Cacna1f
2768,ENSMUSG00000020866,-0.435087,4.029532e-01,NaN,Cacna1g
4278,ENSMUSG00000024112,-1.682962,1.383663e-45,8.771041e-42,Cacna1h
3640,ENSMUSG00000022416,0.204966,7.483576e-01,NaN,Cacna1i
11696,ENSMUSG00000040118,0.480032,2.236196e-05,1.065808e-03,Cacna2d1
1290,ENSMUSG00000010066,0.506137,1.819115e-01,4.858383e-01,Cacna2d2
2780,ENSMUSG00000020882,-0.235226,4.275609e-01,7.221712e-01,Cacnb1
16147,ENSMUSG00000057914,-0.216590,2.771147e-02,1.667581e-01,Cacnb2
565,ENSMUSG00000003352,-0.337967,4.910094e-02,2.308186e-01,Cacnb3
1793,ENSMUSG00000017412,0.179571,8.353959e-01,NaN,Cacnb4

In [13]:
# log2 transform
counts_genes_norm_log2 = pd.read_csv("results_gene_counts_normalized_only_female_231212.csv")   
counts_genes_norm_log2.rename(columns={"Unnamed: 0": "GENEID"}, inplace = True)
cols = counts_genes_norm_log2.columns
counts_genes_norm_log2[cols[1:]] = counts_genes_norm_log2[cols[1:]].apply(np.log2, errors='coerce')

In [14]:
#merge log2 counts and LFC padj results

######################################
goi_counts_norm_log2 = goi.merge(counts_genes_norm_log2, how = "left", 
                           left_on='GENEID', 
                           right_on='GENEID', 
                           validate="one_to_one")
goi_counts_norm_log2.set_index('GENENAME', inplace=True)
######################################

In [18]:
goi_counts_norm_log2.\
sort_values(by=["GENENAME"], ascending=True).\
to_excel("data_l2fc_p__log2counts_calcium_channels_only_female_231212.xlsx")